SCREEN_SIZE_X = 700
SCREEN_SIZE_Y = 500

CAPTION = "FireworkSimulation"
SOUND_VOLUME = 1

PIXEL_SIZE = 4
PIXEL_NUMBER = 100

MAX_RADIUS = 90

MAX_LENGTH = 30
ROCKET_SPEED = 3.2
EXPLOSION_SPEED = 0.01